### ISSUE TITLE
Consider interfacing with repositories via config files rather than GNU Make

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/origin-ci-tool#9]
*This is a question if it has already been considered, or a design suggestion otherwise.*

Instead of requiring every repository to implement certain Make targets, I suggest considering using configuration files instead.

Repositories should be free to use whatever tools they already use / want to use / etc, and by having a documented API in the CI tool, repositories can integrate with it without the tool forcing assumptions on every repository.

E.g., Travis CI reads `.travis.yml`, and you can use that to do arbitrary things. It is also much easier to add functionality to the CI tool that repositories can gradually pick up. You can at some point change API version, etc, etc. All these things are much harder to do when the CI tool is bound to specific make targets (and so are all repositories).

Configuration files also allow giving metadata. I could use a `.octfile` to setup multiple test jobs and give them suggestive names, instead of `make test INTEGRATION=1`, `make test-with-race`, `make test-somethings-only`, ... Compare:

```yaml
---
# .octfile
jobs:
  - name: Integration tests
    command: hack/test-integration
  - name: Unit tests with race detector
    command: go test ./... -race
  - name: Check commit message format
    command: make check-commit-message
```

And with a `oct` CLI tool, it could be smart to do fuzzy matching on job names:

```console
$ oct job integration
... running Integration tests ...
$ oct job intgrtst
... running Integration tests ...
```

But that's just a side-effect of not being bound to GNU Make as an API.
